### PR TITLE
Add support for private-key-path parameter

### PR DESCRIPTION
**Pull request by sbycrosz**
Add support for [private-key-path](https://microsoft.github.io/code-push/articles/CodeSigningAnnouncement.html) parameter for codepush actions :v:

### CODE REVIEW

**Review by marsinchevskaya — APPROVED** [review]

**Review by sergei-fedorov — APPROVED** [review]
Thanks for your contribution!

**Comment by Weegle99** [comment]
Any news? Everything seems to be in order for that PR to be merged

**Comment by brunocrpontes** [comment]
Is something missing to merge this PR? @sergei-fedorov

**Comment by LouisKraemer** [comment]
@sergei-fedorov   Is a new release planned to include this feature in the plugin? Only thing missing on our project to ditch the command line.

**Comment by DmitriyKirakosyan** [comment]
Hi @LouisKraemer , yes we are planning to release fastlane-plugin this month.

**Pull request merged**
